export const DSA_TOPICS = [
  { title: "Arrays", slug: "arrays", description: "Sequential data structures" },
  { title: "Strings", slug: "strings", description: "Text processing techniques" },
  { title: "Sorting Algorithms", slug: "sorting-algorithms", description: "Data ordering techniques" },
  { title: "Hash Tables", slug: "hashing", description: "Key-value storage" },
  { title: "Two Pointers", slug: "two-pointers", description: "Two-pointer techniques" },
  { title: "Prefix Sum", slug: "prefix-sum", description: "Efficient range queries" },
  { title: "Sliding Window", slug: "sliding-window", description: "Efficient window-based algorithms" },
  { title: "Stack", slug: "stack", description: "LIFO data structures" },
  { title: "Binary Search", slug: "binary-search", description: "Logarithmic search algorithms" },
  { title: "Recursion", slug: "recursion", description: "Self-referential functions" },
  { title: "Backtracking", slug: "backtracking", description: "Constraint satisfaction" },
  { title: "Dynamic Programming", slug: "dp", description: "Optimal substructure problems" },
  { title: "Linked List", slug: "linked-list", description: "Dynamic linear structures" },
  { title: "Trees", slug: "trees", description: "Hierarchical data structures" },
  { title: "Graphs", slug: "graphs", description: "Node-edge relationships" },
  { title: "Bit Manipulation", slug: "bit-manipulation", description: "Binary operations" },
];
